services:
  node-a:
    build: .
    ports:
      - "8545:8545"
    volumes:
      - node-a-data:/data:Z
      - ./examples:/examples:z
    command: [ "node", "--data-dir", "/data", "--port", "8545", "--dsl", "/examples/test_registry.vera" ]

  node-b:
    build: .
    ports:
      - "8546:8545"
    volumes:
      - node-b-data:/data:Z
      - ./examples:/examples:z
    command: [ "node", "--data-dir", "/data", "--port", "8545", "--dsl", "/examples/test_registry.vera" ]

  node-c:
    build: .
    ports:
      - "8547:8545"
    volumes:
      - node-c-data:/data:Z
      - ./examples:/examples:z
    command: [ "node", "--data-dir", "/data", "--port", "8545", "--dsl", "/examples/test_registry.vera" ]

volumes:
  node-a-data:
  node-b-data:
  node-c-data:
